name: Build on push

on:
  push:
    branches: main
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: setup nuget
      uses: NuGet/setup-nuget@v1

    - name: build
      run: |
        cd src
        nuget restore
        msbuild /p:platform="Any CPU" /p:configuration="Release"

    - name: upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build
        path: $GITHUB_WORKSPACE/src/bin/
